### ISSUE TITLE
Forced handshake required in some instances to get a new token

### ISSUE THREAD

**Issue by joshbickett** [pjhul/auth0-web-extension#1]
**Assumptions**
I noticed that `getTokenSilently()` returns the same token in many instances. It appears that as long as a service worker is awake the same token will be returned and I assume it just returns the in-memory token instead of doing another handshake for the token. A handshake and new token are only created after the service worker goes to sleep and wakes up again. I am basing this on  Paul's blog post (great post, thanks for making it).

"...the nice thing is that on subsequent calls to getTokenSilently, we can pull from the in-memory cache meaning that it consistently takes less than 1ms to get a token."
https://pjhul.com/blog/auth0-web-extension

**Our issue**
Our issue is that some cases, we need to force a handshake and get a new token instead of using the in-memory cached token. 

For us when users sign up without 3rd party auth0 (sign in with google, etc.), we require email verification via users clicking confirm email in their inbox. The user navigates to Gmail to confirm and the auth0-web-extension process is completed before confirming the email. A token is saved with `emailVerified ` as `false`. After the user confirms their email and goes to a website to use the extension functionality the service worker is still awake and has the old token with `emailVerified` as `false`. The API calls fail because we require it true. 

**Possible solution**

I was thinking we could update `getTokenSilently()` with an argument to optionally force a new handshake. I am open to other ideas and interested in contributing to the repository to improve it. 

Thanks!

**Comment by pjhul** [comment]
Hey Josh, thanks for posting an issue!

If I remember correctly, the `getTokenSilently()` method has an option that you can pass called `ignoreCache` that will bypass the cache check and go straight to grabbing a new token. I took a quick look and it looks like we implement that option. so try giving that a try and let me know if that works for you!

Also, it's been a little while since I've taken a look at this library, but I'm getting back to a point in my own development where I'm going to be using this library again and so I'm planning on getting back to actively developing it. I know you mentioned you were interested in contributing, would you like if I went and opened up a couple issues with things to work on?

**Comment by joshbickett** [comment]
Hey Paul, 

Great, you were right about `ignoreCache`. It fixed our issue, thanks! I think we discussed `ignoreCache` at one point but I forgot. 

Also yes, I think it makes sense to open up some issues to work on. We are relying on this repository for our extension which is gaining users so we are interested in helping improve it. I don't think I can say precisely when we will work on issues, but if we open some issues then our team can monitor and prioritize helping out. 

I think Matt B. and I found another issue as well, so I'll create a post for it. In general, this code is scaling well for us with our extension. 

Thanks!
